# One-shot telemetry setup. Run from Alleral Hub root:
#   powershell -ExecutionPolicy Bypass -File tools/setup_telemetry.ps1
#
# Optional env vars before running:
#   $env:DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/..."
#   $env:TELEMETRY_PUBLIC_URL = "https://your-relay.up.railway.app"  # skip tunnel if set

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$backend = Join-Path $root "backend"
$privateDir = Join-Path (Split-Path -Parent $root) "Alleral-Private"
$privateFile = Join-Path $privateDir "owner_telemetry.luau"
$envFile = Join-Path $backend ".env"

function New-ApiKey {
    python -c "import secrets; print('aller_' + secrets.token_urlsafe(32))"
}

# --- backend/.env ---
if (-not (Test-Path $envFile)) {
    Copy-Item (Join-Path $backend ".env.example") $envFile
}

$envContent = Get-Content $envFile -Raw
$webhook = $env:DISCORD_WEBHOOK_URL
if (-not $webhook) {
    if ($envContent -match 'DISCORD_WEBHOOK_URL=(https://discord\.com/api/webhooks/[^\s]+)') {
        $webhook = $Matches[1]
    }
}
if (-not $webhook) {
    $webhook = Read-Host "Paste your Discord webhook URL"
}

$key = $null
if ($envContent -match 'TELEMETRY_API_KEY=(aller_[^\s]+)') {
    $existing = $Matches[1]
    if ($existing -and $existing -ne "aller_CHANGE_ME" -and $existing.Length -ge 24) {
        $key = $existing
    }
}
if (-not $key) {
    $key = New-ApiKey
}

@"
# Auto-generated by tools/setup_telemetry.ps1 — gitignored
DISCORD_WEBHOOK_URL=$webhook
TELEMETRY_API_KEY=$key

TELEMETRY_BRAND=Alleral Ops
TELEMETRY_HOST=0.0.0.0
TELEMETRY_PORT=8787
TELEMETRY_MAX_QUEUE=5000
TELEMETRY_IP_RATE_PER_MIN=120
TELEMETRY_HEARTBEAT_BATCH_SEC=90
TELEMETRY_DISCORD_INTERVAL_SEC=0.55
"@ | Set-Content -Path $envFile -Encoding UTF8
Write-Host "[ok] backend/.env configured"

pip install -r (Join-Path $backend "requirements.txt") -q

# --- start relay if not running ---
$healthOk = $false
try {
    $r = Invoke-RestMethod -Uri "http://127.0.0.1:8787/health" -TimeoutSec 2
    $healthOk = $r.ok -eq $true
} catch {}

if (-not $healthOk) {
    Write-Host "[..] Starting relay on port 8787..."
    Start-Process -FilePath "python" -ArgumentList "telemetry_relay.py" -WorkingDirectory $backend -WindowStyle Minimized
    Start-Sleep -Seconds 2
    try {
        $r = Invoke-RestMethod -Uri "http://127.0.0.1:8787/health" -TimeoutSec 5
        $healthOk = $r.ok -eq $true
    } catch {}
}
if ($healthOk) { Write-Host "[ok] Relay running at http://127.0.0.1:8787" }
else { Write-Host "[warn] Relay did not start — run: python backend/telemetry_relay.py" }

# --- public URL (Roblox in-game; offline dev uses 127.0.0.1:8787) ---
$publicBase = $env:TELEMETRY_PUBLIC_URL
if (-not $publicBase) {
    $publicBase = "https://alleral-telemetry-production.up.railway.app"
    Write-Host "[ok] Using Railway for Roblox: $publicBase"
    Write-Host "     Offline local relay: http://127.0.0.1:8787 (start with tools/start_relay.ps1)"
}

$relayUrl = ""
if ($publicBase) {
    $publicBase = $publicBase.Trim().TrimEnd("/")
    if ($publicBase -notmatch "/ingest$") {
        $relayUrl = "$publicBase/ingest"
    } else {
        $relayUrl = $publicBase
    }
}

# --- client config (config/ + Alleral-Private/) ---
& (Join-Path $PSScriptRoot "sync_telemetry_config.ps1")

# --- test ingest ---
if ($relayUrl -and $relayUrl -notmatch "YOUR-RELAY") {
    $testUrl = if ($relayUrl -match "^https?://") { $relayUrl } else { "http://127.0.0.1:8787/ingest" }
    if ($publicBase) { $testUrl = $relayUrl }
    else { $testUrl = "http://127.0.0.1:8787/ingest" }

    $body = @{
        event = "inject_loaded"
        timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
        sessionId = "setup-test"
        player = @{ name = "SetupTest"; userId = 1; displayName = "Setup"; accountAge = 0 }
        context = @{
            executor = "setup_script"
            loaderVersion = "5.4.6"
            gameName = "Telemetry Setup"
            scriptName = "test"
            scriptVersion = "1"
            placeId = 0
            jobId = "setup"
        }
    } | ConvertTo-Json -Depth 6

    try {
        $resp = Invoke-RestMethod -Uri $testUrl -Method Post -Headers @{ "X-Alleral-Key" = $key; "Content-Type" = "application/json" } -Body $body
        Write-Host "[ok] Test event accepted: $($resp.status)"
        Write-Host "     Check your Discord Telemetry channel for 'Inject succeeded'"
    } catch {
        Write-Host "[warn] Test ingest failed: $_"
    }
}

Write-Host ""
Write-Host "=== Telemetry setup complete ==="
Write-Host "API key: $key"
Write-Host "Client config: config/owner_telemetry.luau + Alleral-Private/owner_telemetry.luau"
Write-Host "Loader auto-loads these when readfile works (Volt workspace / local files)."
if (-not $publicBase) {
    Write-Host "NEXT: Deploy backend/ to Railway and re-run with TELEMETRY_PUBLIC_URL set."
}
